config/routes.rb
Rails.application.routes.draw do

  constraints host: 'www.disruptiondiagnostic.com' do
    match '(*any)', to: redirect(host: 'disruptiondiagnostic.com'), via: :all
  end

  constraints host: 'scurvelocator.com' do
    match '(*any)', to: redirect(host: 'disruptiondiagnostic.com'), via: :all
  end

  constraints host: 'www.scurvelocator.com' do
    match '(*any)', to: redirect(host: 'disruptiondiagnostic.com'), via: :all
  end

  root to: "visitor#home"

  get  'start_survey', to: redirect('/')
  post 'start_survey', to: 'visitor#start_survey'
  get  'question/:id', to: 'visitor#question',    as: 'q'
  get  'about-you-1',  to: 'visitor#about_you_1', as: 'about_you_1'
  get  'about-you-2',  to: 'visitor#about_you_2', as: 'about_you_2'
  patch 'about-yous',  to: 'visitor#update_about_yous',  as: 'about_yous'
  post 'answer/:id',   to: 'visitor#answer',      as: 'a'
  get  'results',      to: 'visitor#results'

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  devise_scope :user do
    get 'register', to: 'devise/registrations#new'
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy', as: 'logout'
  end

  scope :admin, module: 'admin' do
    root to: 'surveys#index'
    resources :questions, except: [:new, :create, :destroy]
    resources :surveys do
      get 'results/:code', on: :collection, to: 'surveys#company_results', as: :company_results
    end
    scope :charts do
      root to: 'charts#index', as: 'charts'
      get 'data', to: 'charts#data', as: 'charts_data'
    end
    scope :orgs do
      root to: 'orgs#index', as: 'orgs'
      get "new", to: "orgs#new", as: 'new'
      post "create", to: "orgs#create", as: 'create'
      patch "update_team", to: "orgs#update_team", as: 'update_team'
      post "create_team", to: "orgs#create_team", as: 'create_team'
    end
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :team, optional: true
  validates :name, :email, presence: true

  before_save :assign_team

  def assign_team
    if self.team_name
      team = Team.find_or_create_by(name: self.team_name.downcase)
    else
      team = Team.random_team
    end
    self.team_id = team.id
  end

  def score
    answers.map(&:answer_before_type_cast).reduce(&:+)
  end

  def first_name
    if name.split.count > 1
      name.split[0..-2].join(' ')
    else
      name
    end
  end

  def last_name
    if name.split.count > 1
      name.split.last
    end
  end

  def self.average_score_for(team_id)
    return nil if team_id.blank?

    Survey.where(team_id: team_id).map(&:score).compact.then{ |arr| arr.inject(:+).to_f / arr.length }
  end
end

app/controllers/admin/surveys_controller.rb
class Admin::SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @score = @survey.score
    @hide_pdf = true
    render 'visitor/results'
  end

  # GET /surveys/1/edit
  def edit
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to surveys_url, notice: 'Response was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Response was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def company_results
    @score = Survey.average_score_for(params.require(:code))
    @hide_pdf = true
    render 'visitor/results'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.where(id: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name, :email, :code)
    end
end

app/views/admin/surveys/_form.html.erb
<%= form_with(model: survey, class:"intro", local: true) do |form| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <ul class="errors">
      <% survey.errors.full_messages.each do |message| %>
        <li class="error"><i class="fas fa-exclamation-triangle"></i><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :code %>
    <%= form.text_field :code, class: "form-control" %>
  </div>

<div class="actions-container">
  <div class="actions">
    <%= form.submit "Save", class: 'form-control' %>
  </div>
<% end %>

app/views/admin/surveys/_mini_answers.html.erb
<span>
  <% answers.includes(:question).order(:question_id).each do |answer| %>
    <%= link_to answer.initial, "#", title: "#{answer.question.category}", onclick: "return false;" %>
  <% end %>
</span>

app/views/admin/surveys/edit.html.erb
<h1 class="container edit-states">Editing Response</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Cancel', surveys_path, class: "cancel" %>
</div>

app/views/admin/surveys/index.html.erb
<header class="admin-header container">
    <div class="toggle">
        <%= link_to "Responses", surveys_url, class: "active-toggle" %>
        <%= link_to "Questions", questions_url, class: "inactive-toggle" %>
        <%= link_to "Charts", charts_url, class: "inactive-toggle" %>
    </div>
    <div>
        <%= link_to "Sign out", logout_path, class: 'new logout' %>
    </div>
</header>
<section class="container">
    <table class="table-striped" data-controller="datatable">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Company ID</th>
          <th>Score</th>
          <th>Answers</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @surveys.each do |survey| %>
          <tr>
            <td><%= survey.name %></td>
            <td><%= survey.email %></td>
            <td><%= link_to survey.team_name, company_results_surveys_path(survey.team_id) %></td>
            <td><%= survey.score %></td>
            <td><%= render 'mini_answers', answers: survey.answers %></td>
            <td>
              <%= link_to 'View score', survey %>
              <%= link_to 'Edit', edit_survey_path(survey) %>
              <%= link_to 'Delete', survey, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
</section>