config/routes.rb
Rails.application.routes.draw do

  constraints host: 'www.disruptiondiagnostic.com' do
    match '(*any)', to: redirect(host: 'disruptiondiagnostic.com'), via: :all
  end

  constraints host: 'scurvelocator.com' do
    match '(*any)', to: redirect(host: 'disruptiondiagnostic.com'), via: :all
  end

  constraints host: 'www.scurvelocator.com' do
    match '(*any)', to: redirect(host: 'disruptiondiagnostic.com'), via: :all
  end

  root to: "visitor#home"

  get  'start_survey', to: redirect('/')
  post 'start_survey', to: 'visitor#start_survey'
  get  'question/:id', to: 'visitor#question',    as: 'q'
  get  'about-you-1',  to: 'visitor#about_you_1', as: 'about_you_1'
  get  'about-you-2',  to: 'visitor#about_you_2', as: 'about_you_2'
  patch 'about-yous',  to: 'visitor#update_about_yous',  as: 'about_yous'
  post 'answer/:id',   to: 'visitor#answer',      as: 'a'
  get  'results',      to: 'visitor#results'

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  devise_scope :user do
    get 'register', to: 'devise/registrations#new'
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy', as: 'logout'
  end

  scope :admin, module: 'admin' do
    root to: 'surveys#index'
    resources :questions, except: [:new, :create, :destroy]
    resources :surveys do
      get 'results/:code', on: :collection, to: 'surveys#company_results', as: :company_results
    end
    scope :charts do
      root to: 'charts#index', as: 'charts'
      get 'data', to: 'charts#data', as: 'charts_data'
    end
    scope :orgs do
      root to: 'orgs#index', as: 'orgs'
      get "new", to: "orgs#new", as: 'new'
      post "create", to: "orgs#create", as: 'create'
      patch "update_team", to: "orgs#update_team", as: 'update_team'
      post "create_team", to: "orgs#create_team", as: 'create_team'
    end
  end
end

app/controllers/visitor_controller.rb
class VisitorController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_survey, only: [:question, :answer, :about_you_1, :about_you_2, :update_about_yous]

  def home
    @survey = Survey.new
  end

  def start_survey
    @survey = Survey.new(survey_params)
    
    respond_to do |format|
      if @survey.save
        session[:survey_id] = @survey.id
        format.html { redirect_to q_url(1) }
        save_user_to_convertkit(@survey)
      else
        format.html { render :home }
      end
    end
  end

  def question
    @question = Question.find_by(sort_order: params[:id])
    @answer = Answer.find_or_initialize_by(survey: @survey, question: @question)
    @page_number = params[:id].to_i
    @progress_pct = 100*@page_number/Question.end
  end

  def about_you_1
  end

  def about_you_2
  end

  def update_about_yous
    @survey.update(survey_params)
  end

  def answer
    @question = Question.find_by(sort_order: params[:id])
    @answer = Answer.find_or_initialize_by(survey: @survey, question: @question)
    @answer.update!(answer_params)
  end

  def results
    if params[:score].present?
      @score = params[:score].to_i
    else
      set_survey
      return if @survey.blank?
      @score = @survey.score
    end
    respond_to do |format|
      format.html
      format.pdf do
        pdf = Tempfile.new("pdf-chrome-puppeteer").path + '.pdf'
        url = results_url(score: @score)
        system("node save-as-pdf.js #{Shellwords.escape(url)} #{Shellwords.escape(pdf)}")
        send_file(pdf, filename: "results.pdf", type: 'application/pdf', disposition: 'inline')
      end
    end
  end

  private

  def set_survey
    unless @survey = Survey.find_by_id(session[:survey_id])
      redirect_to root_url
    end
  end

  def survey_params
    params.require(:survey).permit(:name, :email, :team_name, :age, :industry, :how_long_in_role, :gender, :intention_to_use_feedback, :next_steps, :what_information, :how_can_we_improve)
  end

  def answer_params
    params.require(:answer).permit(:answer)
  end

  def save_user_to_convertkit(survey)
    api_key = ENV.fetch("CONVERTKIT_API_KEY") { nil }

    return if api_key.blank?

    body = JSON.generate({
      api_key: api_key,
      email: survey.email,
      first_name: survey.first_name,
      fields: {
        last_name: survey.last_name,
      }
    })
    #Faraday.post("https://api.convertkit.com/v3/forms/1033788/subscribe", body, "Content-Type" => "application/json")
  end
end

app/views/visitor/about_you_1.html.erb
<section class="question-container">
    <div class="logo-question">
        <%= image_tag 'dd_logo.svg', class: 'dd_logo', alt: 'disruption diagnostic logo' %>
    </div>

    <section class="container question">
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"
              style="width: <%= number_to_percentage(@progress_pct, precision: 0) %>">
            </div>
        </div>

        <div class="wrapper">
            <p class="question-text">About You</p>

            <%= form_with model: @survey, class: 'responses', url: about_yous_path, method: :patch do |form| %>
                <p class="my-2"><strong>Share Your Age</strong></p>
                <%= form.radio_button :age, '17', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "age_17", "17 years or younger" %><br>
                <%= form.radio_button :age, '18-24', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "age_18-24", "18-24" %><br>
                <%= form.radio_button :age, '25-34', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "age_25-34", "25-34" %><br>
                <%= form.radio_button :age, '35-44', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "age_35-44", "35-44" %><br>
                <%= form.radio_button :age, '45-54', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "age_45-54", "45-54" %><br>
                <%= form.radio_button :age, '55-64', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "age_55-64", "55-64" %><br>
                <%= form.radio_button :age, '65-74', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "age_65-74", "65-74" %><br>
                <%= form.radio_button :age, '75-up', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "age_75-up", "75 or older" %><br>
                <%= form.radio_button :age, 'not_disclosed', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "age_not_disclosed", "Prefer not to answer" %><br>

                <p class="my-2"><strong>Please indicate your industry or department.</strong></p>
                <%= form.text_field :industry, class: 'form-control', onchange: '$(this.form).trigger("submit.rails");' %>

                <p class="my-2"><strong>How long have you held your current role?</strong></p>
                <%= form.radio_button :how_long_in_role, 'less_than_1', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "how_long_in_role_less_than_1", "Less than a year" %><br>
                <%= form.radio_button :how_long_in_role, '1-2', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "how_long_in_role_1-2", "1-2 years" %><br>
                <%= form.radio_button :how_long_in_role, '3-4', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "how_long_in_role_3-4", "3-4 years" %><br>
                <%= form.radio_button :how_long_in_role, '5-6', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "how_long_in_role_5-6", "5-6 years" %><br>
                <%= form.radio_button :how_long_in_role, '6-up', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "how_long_in_role_6-up", "more than 6 years" %><br>

                <p class="my-2"><strong>Please indicate your gender.</strong></p>
                <%= form.radio_button :gender, 'female', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "gender_female", "Female" %><br>
                <%= form.radio_button :gender, 'male', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "gender_male", "Male" %><br>
                <%= form.radio_button :gender, 'not_disclosed', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "gender_not_disclosed", "Prefer not to answer" %><br>
            <% end %>

            <div class="prev-next-buttons">
                <%= link_to "Back", q_path(Question.end) %>
                <%= link_to "Next", about_you_2_path %>
            </div>
        </div>
    </section>

</section>

app/views/visitor/about_you_2.html.erb
<section class="question-container">
    <div class="logo-question">
        <%= image_tag 'dd_logo.svg', class: 'dd_logo', alt: 'disruption diagnostic logo' %>
    </div>

    <section class="container question">
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"
              style="width: <%= number_to_percentage(@progress_pct, precision: 0) %>">
            </div>
        </div>

        <div class="wrapper">
            <p class="question-text">More About You</p>

            <%= form_with model: @survey, class: 'responses', url: about_yous_path, method: :patch do |form| %>
                <p class="my-2"><strong>How likely are you to use the feedback from the S Curve Locator as a decision aid in defining your next steps and/or managing your career path?</strong></p>
                <%= form.radio_button :intention_to_use_feedback, 'very_likely', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "intention_to_use_feedback_very_likely", "Very Likely" %><br>
                <%= form.radio_button :intention_to_use_feedback, 'likely', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "intention_to_use_feedback_likely", "Likely" %><br>
                <%= form.radio_button :intention_to_use_feedback, 'neutral', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "intention_to_use_feedback_neutral", "Neutral" %><br>
                <%= form.radio_button :intention_to_use_feedback, 'unlikely', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "intention_to_use_feedback_unlikely", "Unlikely" %><br>
                <%= form.radio_button :intention_to_use_feedback, 'very_unlikely', onchange: '$(this.form).trigger("submit.rails");' %> <%= form.label "intention_to_use_feedback_very_unlikely", "Very unlikely" %><br>

                <p class="my-2"><strong>Based on the outputs of the S Curve Locator, what next steps are you going to take? What next steps would you want help defining or putting into action?</strong></p>
                <%= form.text_area :next_steps, class: 'form-control', onchange: '$(this.form).trigger("submit.rails");' %>

                <p class="my-2"><strong>What information would you want more of? What information would you want less of?</strong></p>
                <%= form.text_area :what_information, class: 'form-control', onchange: '$(this.form).trigger("submit.rails");' %>

                <p class="my-2"><strong>If you are not likely to use the output, why and what would make it more useful for you?</strong></p>
                <%= form.text_area :how_can_we_improve, class: 'form-control', onchange: '$(this.form).trigger("submit.rails");' %>
            <% end %>

            <div class="prev-next-buttons">
                <%= link_to "Back", about_you_1_path %>
                <%= link_to "See results", results_path %>
            </div>
        </div>
    </section>

</section>

app/views/visitor/home.html.erb
<section class="container-home">
    <header class="container log-in w-100">
        <div class="logo">
            <%= image_tag 'dd_logo.svg', class: 'dd_logo', alt: 'disruption diagnostic logo' %>
        </div>
        <h1 class="container center title">Dare to disrupt yourself!</h1>
    </header>

    <div class="container w-100">
      <%= form_with model: @survey, class: 'intro visitor-intro sign-in-pages', url: start_survey_path, local: true do |form| %>

        <% if @survey.errors.any? %>
          <div id="error_explanation">
            <ul class="errors">
            <% @survey.errors.full_messages.each do |message| %>
              <li class="error"><i class="fas fa-exclamation-triangle"></i><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :email %>
          <%= form.text_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :team_name, "Team Name (optional)"%>
          <%= form.text_field :team_name, class: 'form-control' %>
        </div>

        <div class="form-group remove-margin">
          <%= form.submit "Start", class: 'form-control start-button' %>
        </div>
      <% end %>
    </div>

</section>

app/views/visitor/question.html.erb
<section class="question-container">
    <div class="logo-question">
        <%= image_tag 'dd_logo.svg', class: 'dd_logo', alt: 'disruption diagnostic logo' %>
    </div>

    <section class="container question">
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"
              style="width: <%= number_to_percentage(@progress_pct, precision: 0) %>">
            </div>
        </div>

        <div class="wrapper">
            <p class="question-text"><%= @question.category.titleize %></p>
            <p class="question-sub-text"><%= @question.prompt %></p>

            <%= form_with model: @answer, class: 'responses', url: a_path(params[:id]), method: :post do |form| %>
              <% [:low, :mid, :high].shuffle.each do |level| %>
                <p>
                  <%= form.radio_button :answer, level, onchange: '$(this.form).trigger("submit.rails");' %>
                  <%= form.label "answer_#{level}", @question.send(level) %>
                </p>
              <% end %>
            <% end %>

            <div class="prev-next-buttons">
                <% if @page_number == 1 %>
                    <div class="prev-next-buttons reverse">
                        <%= link_to "Next", q_path(@page_number + 1), class: "question-1" %>
                        <div class='page-numbers'>
                            <%= @page_number %>/10
                        </div>
                    </div>
                <% elsif @page_number > 1 %>
                    <%= link_to "Back", q_path(@page_number - 1) %>
                    <div class='page-numbers'>
                        <%= @page_number %>/10
                    </div>
                <% end %>

                <% if @page_number > 1 && @page_number < Question.end %>
                    <%= link_to "Next", q_path(@page_number + 1) %>
                <% elsif @page_number == Question.end %>
                    <%= link_to "Next", about_you_1_path %>
                <% end %>
            </div>
        </div>
    </section>

</section>

app/views/visitor/results.html.erb
<section class=" red-top">
</section>
<section class="results-container">
    <div class="logo-results">
        <%= image_tag 'dd_logo.svg', class: 'dd_logo', alt: 'disruption diagnostic logo' %>
    </div>
    <div class="results">
        <p class="score-is">Your S curve Score is:</p>
        <h1 id="score"><%= @score || "??" %></h1>
        <p class="score-explain container"><%= score_explanation(@score) %></p>
        <% unless @hide_pdf %>
          <p class="save-as-pdf"><%= link_to "Save as PDF", results_path(format: :pdf), target: 'blank'%></p>
        <% end %>
    </div>
</section>

    <section class="graph-bg">
        <div id="chartContainer">
            <%= image_tag 'graph.png', class: 'graph', alt: 's-score graph' %>
        </div>
    </section>


<section class="results-container">
     <section class="helpful-links">
        <h2>Helpful Links</h2>
        <ul>
            <li><a href="https://hbr.org/2012/09/throw-your-life-a-curve" target="blank">Learn more about the S-curve.</a></li>
            <li><a href="http://amzn.to/2lBMO41" target="blank">Read Chapter 1 of Disrupt Yourself.</a></li>
            <li><a href="http://whitneyjohnson.com/hbr-what-to-do-when-your-personal-growth-stalls/" target="blank">Read What Happens When Personal Growth Stalls.</a></li>
            <li><a href="http://whitneyjohnson.com/linkedin-maybe-woody-allen-was-right-80-of-success-is-just-showing-up/" target="blank">Read more about showing up to new challenges.</a></li>
            <li><a href="http://amzn.to/2lBMO41" target="blank">Read more about "Driving Discovery" in Chapter 7 of Disrupt Yourself.</a></li>
            <li><a href="http://whitneyjohnson.com/make-your-innovative-idea-seem-less-terrifying/" target="blank">As you consider your next move, read How to Make an Innovative Idea Less Terrifying.</a></li>
        </ul>
    </section>


</section>