config/routes.rb
Rails.application.routes.draw do

  constraints host: 'www.disruptiondiagnostic.com' do
    match '(*any)', to: redirect(host: 'disruptiondiagnostic.com'), via: :all
  end

  constraints host: 'scurvelocator.com' do
    match '(*any)', to: redirect(host: 'disruptiondiagnostic.com'), via: :all
  end

  constraints host: 'www.scurvelocator.com' do
    match '(*any)', to: redirect(host: 'disruptiondiagnostic.com'), via: :all
  end

  root to: "visitor#home"

  get  'start_survey', to: redirect('/')
  post 'start_survey', to: 'visitor#start_survey'
  get  'question/:id', to: 'visitor#question',    as: 'q'
  get  'about-you-1',  to: 'visitor#about_you_1', as: 'about_you_1'
  get  'about-you-2',  to: 'visitor#about_you_2', as: 'about_you_2'
  patch 'about-yous',  to: 'visitor#update_about_yous',  as: 'about_yous'
  post 'answer/:id',   to: 'visitor#answer',      as: 'a'
  get  'results',      to: 'visitor#results'

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  devise_scope :user do
    get 'register', to: 'devise/registrations#new'
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy', as: 'logout'
  end

  scope :admin, module: 'admin' do
    root to: 'surveys#index'
    resources :questions, except: [:new, :create, :destroy]
    resources :surveys do
      get 'results/:code', on: :collection, to: 'surveys#company_results', as: :company_results
    end
    scope :charts do
      root to: 'charts#index', as: 'charts'
      get 'data', to: 'charts#data', as: 'charts_data'
    end
    scope :orgs do
      root to: 'orgs#index', as: 'orgs'
      get "new", to: "orgs#new", as: 'new'
      post "create", to: "orgs#create", as: 'create'
      patch "update_team", to: "orgs#update_team", as: 'update_team'
      post "create_team", to: "orgs#create_team", as: 'create_team'
    end
  end
end

app/controllers/admin/orgs_controller.rb
class Admin::OrgsController < ApplicationController

  def index
    @random_organisation = Organisation.random_organisation
    @random_teams = @random_organisation.teams
    @all_organisations = Organisation.all - [@random_organisation]
  end

  def new
    @organisation = Organisation.new
  end

  def create
    @organisation = Organisation.new(organisation_params)
    respond_to do |format|
      if @organisation.save
        format.html { redirect_to orgs_url }
      else
        format.html { render :new }
      end
    end
  end
  
  def update_team
    @team = Team.find(params[:team_id])
    @organisation = Organisation.find(params[:org_id])
    @random_organisation = Organisation.random_organisation
    @all_organisations = Organisation.all - [@random_organisation]
    if @team.update(organisation_id: @organisation.id)
      render json: {message: "Team is updated successfully!"}
    end
  end

  def create_team
    @organisation = Organisation.where(id: params[:org_id]).first || Organisation.random_organisation

    @team = Team.new(name: params[:team_name], organisation_id: @organisation.id)
    
    if @team.save
      render json: {message: "Team is created successfully!"}
    end
  end

  private

  def organisation_params
    params.require(:organisation).permit(:name)
  end
end

app/views/admin/orgs/index.html.erb
<header class="admin-header container">
    <div class="toggle">
        <%= link_to "Responses", surveys_url, class: "inactive-toggle" %>
        <%= link_to "Questions", questions_url, class: "inactive-toggle" %>
        <%= link_to "Charts", charts_url, class: "inactive-toggle" %>
        <%= link_to "Orgs", orgs_url, class: "active-toggle" %>
    </div>
    <div>
        <%#= link_to 'New Question', new_question_path, class: "new" %>
        <a class="new logout" href="#logout">Sign out</a>
    </div>
</header>
<section class="container">

  <table class="table table--orgs">
    <thead>
      <tr>
        <th scope="col">Ungrouped Team</th>
        <th scope="col">Add to:</th>
      </tr>
    </thead>
    <tbody>
      <% @random_teams.each do |team| %>
        <tr>
          <td><%= team.name.humanize %></td>
          <td>
            <select class="custom-select" onchange="updateTeam(this)" data-team-id="<%= team.id %>">
              <option selected>Open this select menu</option>
              <% @all_organisations.each do |org| %>
                <option value="<%= org.id %>"><%= org.name.humanize %></option>
              <% end %>
            </select>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="row mt-5">
    <div class="col">
      <a href="<%= new_path %>" class="btn btn-outline-primary">+ New Org</a>
    </div>
  </div>

  <% @all_organisations.each do |org| %>

    <table class="table table--orgs mt-5">
      <thead>
        <tr>
          <th><%= org.name.humanize %></th>
          <th>Member of:</th>
        </tr>
      </thead>
      <tbody>
        <% org.teams.each do |team| %>
          <tr>
            <td><%= team.name %></td>
            <td>
              <select class="custom-select" onchange="updateTeam(this)" data-team-id="<%= team.id %>">
                <% @all_organisations.each do |org| %>
                  <option value="<%= org.id %>" <%= team.organisation_id == org.id ? "selected" : "" %> ><%= org.name.humanize %></option>
                <% end %>
              </select>
            </td>
          </tr>
        <% end %>
        <tr>
          <td>
            <div class="input-group mb-3 w-50">
              <input type="text" id="team_name-<%= org.id %>"class="form-control" placeholder="New Team" aria-label="Recipient's username" aria-describedby="button-addon2">
              <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="button-addon2" onclick="addTeam(this)" data-org-id="<%= org.id %>">Add Team</button>
              </div>
            </div>
          </td>
          <td></td>
        </tr>
      </tbody>
    </table>

  <% end %>

</section>


<script type="text/javascript">
  function updateTeam(element){
    team_id = $(element).attr("data-team-id")
    org_id = $(element).val()
    $.ajax({
      url: "<%= update_team_path %>",
      method: "patch",
      data: {team_id: team_id, org_id: org_id},
      success: function(data, response){
        window.location.reload()
      },
      error: function(data, response){
        alert("Error updating team!")
      }
    })
  }
  function addTeam(element){
    org_id = $(element).attr("data-org-id")
    team_name = $("#team_name-"+org_id).val()
    $.ajax({
      url: "<%= create_team_path %>",
      method: "post",
      data: {team_name: team_name, org_id: org_id},
      success: function(data, response){
        window.location.reload()
      },
      error: function(data, response){
        alert("Error creating team!")
      }
    })
  }
</script>

app/views/admin/orgs/new.html.erb
<%= form_with(model: @organisation, class:"intro", local: true, url: create_path) do |form| %>
  <% if @organisation.errors.any? %>
    <div id="error_explanation">
      <ul class="errors">
      <% @organisation.errors.full_messages.each do |message| %>
        <li class="error"><i class="fas fa-exclamation-triangle"></i><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

<div class="actions-container">
  <div class="actions">
    <%= form.submit "Save", class: 'form-control' %>
  </div>
<% end %>