config/routes.rb
Rails.application.routes.draw do

  constraints host: 'www.disruptiondiagnostic.com' do
    match '(*any)', to: redirect(host: 'disruptiondiagnostic.com'), via: :all
  end

  constraints host: 'scurvelocator.com' do
    match '(*any)', to: redirect(host: 'disruptiondiagnostic.com'), via: :all
  end

  constraints host: 'www.scurvelocator.com' do
    match '(*any)', to: redirect(host: 'disruptiondiagnostic.com'), via: :all
  end

  root to: "visitor#home"

  get  'start_survey', to: redirect('/')
  post 'start_survey', to: 'visitor#start_survey'
  get  'question/:id', to: 'visitor#question',    as: 'q'
  get  'about-you-1',  to: 'visitor#about_you_1', as: 'about_you_1'
  get  'about-you-2',  to: 'visitor#about_you_2', as: 'about_you_2'
  patch 'about-yous',  to: 'visitor#update_about_yous',  as: 'about_yous'
  post 'answer/:id',   to: 'visitor#answer',      as: 'a'
  get  'results',      to: 'visitor#results'

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  devise_scope :user do
    get 'register', to: 'devise/registrations#new'
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy', as: 'logout'
  end

  scope :admin, module: 'admin' do
    root to: 'surveys#index'
    resources :questions, except: [:new, :create, :destroy]
    resources :surveys do
      get 'results/:code', on: :collection, to: 'surveys#company_results', as: :company_results
    end
    scope :charts do
      root to: 'charts#index', as: 'charts'
      get 'data', to: 'charts#data', as: 'charts_data'
    end
    scope :orgs do
      root to: 'orgs#index', as: 'orgs'
      get "new", to: "orgs#new", as: 'new'
      post "create", to: "orgs#create", as: 'create'
      patch "update_team", to: "orgs#update_team", as: 'update_team'
      post "create_team", to: "orgs#create_team", as: 'create_team'
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  validates :category, :low, :mid, :high, presence: true

  def self.start
    1
  end

  def self.end
    self.all.count
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_url, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to questions_url, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:category, :low, :mid, :high)
    end
end

app/views/admin/questions/_form.html.erb
<%= form_with(model: question, class:"intro", local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <ul class="errors">
      <% question.errors.full_messages.each do |message| %>
        <li class="error"><i class="fas fa-exclamation-triangle"></i><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :category %>
    <%= form.text_area :category, rows: 4, class: "form-control wrapping-input" %>
  </div>

  <div class="field form-group">
    <%= form.label :prompt %>
    <%= form.text_area :prompt, rows: 4, class: "form-control wrapping-input" %>
  </div>

  <div class="field form-group">
    <%= form.label :high %>
    <%= form.text_area :high, rows: 4, class: "form-control wrapping-input" %>
  </div>

  <div class="field form-group">
    <%= form.label :mid %>
    <%= form.text_area :mid, rows: 4, class: "form-control wrapping-input" %>
  </div>

  <div class="field form-group remove-margin">
    <%= form.label :low %>
    <%= form.text_area :low, rows: 4, class: "form-control wrapping-input" %>
  </div>
<div class="actions-container">
  <div class="actions">
    <%= form.submit "Save", class: 'form-control' %>
  </div>
<% end %>

app/views/admin/questions/edit.html.erb
<h1 class="container edit-states">Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Cancel', questions_path, class: "cancel" %>
</div>

app/views/admin/questions/index.html.erb
<header class="admin-header container">
    <div class="toggle">
        <%= link_to "Responses", surveys_url, class: "inactive-toggle" %>
        <%= link_to "Questions", questions_url, class: "active-toggle" %>
        <%= link_to "Charts", charts_url, class: "inactive-toggle" %>
    </div>
    <div>
        <%#= link_to 'New Question', new_question_path, class: "new" %>
        <a class="new logout" href="#logout">Sign out</a>
    </div>
</header>
<section class="container">
    <table class="table-striped" data-controller="datatable">
      <thead>
        <tr>
          <th>Number</th>
          <th>Category</th>
          <th>Prompt</th>
          <th>Low</th>
          <th>Mid</th>
          <th>High</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @questions.each do |question| %>
          <tr>
            <td><%= question.sort_order %></td>
            <td><%= question.category %></td>
            <td><%= question.prompt %></td>
            <td><%= question.low %></td>
            <td><%= question.mid %></td>
            <td><%= question.high %></td>
            <td><%= link_to 'Edit', edit_question_path(question) %><%#= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</section>

app/views/admin/questions/new.html.erb
<h1 class="container edit-states">New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Cancel', questions_path, class: "cancel" %>
</div>

app/views/admin/questions/show.html.erb
<p>
  <strong>Category:</strong>
  <%= @question.category %>
</p>

<p>
  <strong>Prompt:</strong>
  <%= @question.prompt %>
</p>

<p>
  <strong>Low:</strong>
  <%= @question.low %>
</p>

<p>
  <strong>Mid:</strong>
  <%= @question.mid %>
</p>

<p>
  <strong>High:</strong>
  <%= @question.high %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>